### ISSUE TITLE
知乎抓取问题

### ISSUE THREAD

**Issue by huyues** [7sDream/zhihu-oauth#106]
抓取知乎赞同文章几条后出现问题，其他抓取没有问题
Traceback (most recent call last):
  File "D:\Downloads\Music\zhihu2.py", line 13, in <module>
    print(act.target.title)
  File "C:\Users\huys\AppData\Local\Programs\Python\Python35\lib\idlelib\PyShell.py", line 1344, in write
    return self.shell.write(s, self.tags)
UnicodeEncodeError: 'UCS-2' codec can't encode characters in position 13-13: Non-BMP character not supported in Tk

**Comment by 7sDream** [comment]
提供下具体操作的条目 ID 或者相关信息吧，信息太少不好复现。
