### ISSUE TITLE
部分话题的索引不能使用

### ISSUE THREAD

**Issue by xuwenyihust** [7sDream/zhihu-oauth#119]
[issue67](https://github.com/7sDream/zhihu-oauth/issues/67#issuecomment-296392977)下的范例仍然可以正常运行，但当把话题从程序员换成历史，游戏等等其它一些话题时，出现
```
Traceback (most recent call last):
  File "src/topic_collector.py", line 26, in <module>
    index = topic.index.sections
  File "/Users/wenyixu/Coding/data-pipeline-zhihu/env/lib/python3.6/site-packages/zhihu_oauth/zhcls/other.py", line 58, in wrapper
    cache, self._session, cls=obj_cls
  File "/Users/wenyixu/Coding/data-pipeline-zhihu/env/lib/python3.6/site-packages/zhihu_oauth/zhcls/utils.py", line 87, in build_zhihu_obj_from_dict
    return obj_cls(obj_id, data if use_cache else None, session)
  File "/Users/wenyixu/Coding/data-pipeline-zhihu/env/lib/python3.6/site-packages/zhihu_oauth/zhcls/utils.py", line 59, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/wenyixu/Coding/data-pipeline-zhihu/env/lib/python3.6/site-packages/zhihu_oauth/zhcls/topic.py", line 180, in __init__
    self._get_data()
  File "/Users/wenyixu/Coding/data-pipeline-zhihu/env/lib/python3.6/site-packages/zhihu_oauth/zhcls/base.py", line 79, in _get_data
    raise e
zhihu_oauth.exception.GetDataErrorException: A error happened when get data: 资源不存在
```
报错。

**Comment by 7sDream** [comment]
![programmer](https://user-images.githubusercontent.com/7822577/40042499-37607c14-5854-11e8-8e27-59a5255f02e8.png)

![history](https://user-images.githubusercontent.com/7822577/40042505-3bee62a0-5854-11e8-8b21-7146c795878e.png)

并不是所有话题都有索引的~

**Comment by rainyuxia0112** [comment]
那什么function可以把讨论下面的爬取？
