### ISSUE TITLE
当 article 或者 answer 在执行 save 操作时 若文件名中有 \n 则会导致保存失败

### ISSUE THREAD

**Issue by cxgreat2014** [7sDream/zhihu-oauth#23]
当article或者answer在执行save操作时 若文件名中有\n则会导致保存失败
如：这个问题：https://www.zhihu.com/question/36036351

```pytb
Traceback (most recent call last):
  File "bpc.py", line 27, in <module>
    answer.save(collection.title, name)
  File "/usr/lib/python2.7/site-packages/zhihu_oauth/zhcls/answer.py", line 205, in save
    self.author.name, invalid_chars)
  File "/usr/lib/python2.7/site-packages/zhihu_oauth/zhcls/utils.py", line 167, in common_save
    with open(full_path, 'wb') as f:
IOError: [Errno 71] Protocol error: u'\u5e94\u7269\u4e0d\u8ff7--\u4eba\u95f4\u53d6\u820d/\u5982\u4f55\u5efa\u7acb\u575a\u5b9a\u4e0d\u79fb\u7684\u4e16\u754c\u89c2\uff1f\u627e\u5230\u4fe1\u4ef0\uff1f\n.html'
````

**Comment by 7sDream** [comment]
上面那个问题补个网址吧，我好查

**Comment by cxgreat2014** [comment]
ok ，已补 https://www.zhihu.com/question/36036351

**Comment by cxgreat2014** [comment]
问题已找到，当文件要存储的路径为在virtualbox上运行的linux下通过virtualbox提供的共享目录功能挂载的windows目录中时文件名中若有换行符便会触发此错误😂谢谢您了~

**Comment by 7sDream** [comment]
然而 Windows 上有这个 bug 也是要修的~

**Comment by 7sDream** [comment]
在 0.0.19 版本中已修复。
