### ISSUE TITLE
token方式登录时能否自动输入账号密码？

### ISSUE THREAD

**Issue by doradayel** [7sDream/zhihu-oauth#31]
目前借助本项目写了个定时爬取timeline并推送到Kindle上的程序，部署在VPS上。但每隔一段时间token会过期，需要手动登录VPS输入账号密码更新token file。建议在token无效的情况下能使用预设的账号密码，而不是必须手动输入。

exception提示如下：
[2016-10-05 19:00:01] base.py[line:131] ERROR Job "custom_fuction (trigger: cron[hour='19', minute='0'], next run at: 2016-10-06 19:00:00 UTC)" raised an exception
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.5/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/infocenter/InfoCenter/BasicAgents.py", line 70, in custom_fuction
    ebook_path = object_crawler.run()
  File "/root/infocenter/InfoCenter/CustomApps/zhihu_timeline.py", line 65, in run
    following_peoples = [p for p in me.followings]
  File "/root/anaconda3/lib/python3.5/site-packages/zhihu_oauth/zhcls/generator.py", line 354, in wrapper
    self._get_data()
  File "/root/anaconda3/lib/python3.5/site-packages/zhihu_oauth/zhcls/base.py", line 73, in _get_data
    raise e
zhihu_oauth.exception.GetDataErrorException: A error happened when get data: 访问令牌已过期

**Comment by 7sDream** [comment]
恩，知乎令牌好像确实提供了刷新机制，但是我暂时还没写，下个版本补吧……主要是这东西测试起来比较麻烦……

你暂时用个 `try except` 把第一句获取数据的代码包一下，如果有 `GetDataErrorException` 的话就再用 `client.login()` 函数登录一下，再储存新的 Token，重启任务。

我尽量早点把刷新写出来吧……本来国庆是有时间的，结果我电脑坏了 Orz

**Comment by Darmody** [comment]
@7sDream 请问 refresh token 的 API 是什么？

**Comment by 7sDream** [comment]
@Darmody 

现在我还没写呢，所以就没去研究……So 我暂时也不知道 QwQ

你可以自己先研究下试试~

**Comment by Darmody** [comment]
@7sDream OK, 非常感谢，在做一个和知乎有关的app，这个 repo 给了我很多帮助。

**Comment by 7sDream** [comment]
@Darmody 你说的是这个 API 列表么：https://github.com/7sDream/zhihu-oauth/blob/master/zhihu_oauth/zhcls/urls.py

233，有帮助就好~

其实我也还有几个 API 没找到，比如文章的点赞者……如果你找到了麻烦告诉我一声 =，=

**Comment by doradayel** [comment]
@7sDream 好的，不急，大约2-3周才过期一次，一般看到哪天没推送我就手动刷新了。

感谢隔壁的师弟，给我省了老多刷知乎的时间了。

**Comment by ayanamist** [comment]
这个还会更新么，refresh_token的机制和登录几乎是一样的，只是grant_type那里是refresh_token，然后不传username和password，而是传refresh_token，值是client._token._refresh_token的值

**Comment by 7sDream** [comment]
@ayanamist 

在计划列表里，**但是优先级并不太高**，下一版本估计会先解决知乎类的 ID 类型不一致的那个 Bug #68 

我也看过了发的数据和格式，确实不难写……但是和现有代码怎么合并，提供怎样的接口我还需要想想……

因为现在 `ZhihuClient` 和 `Token` 是分离的，而且大家一般会把 Token 存到文件……

只有在访问网络获取到的数据不符合预期时才能知道 Token 过期，但这时候都是在用户逻辑里……更新的话需要抛错误然后用户处理……就还是很不爽……

现在计划是提供两个接口： `ZhihuClient.is_valid_token()` 和 `ZhihuClient.refresh_token(save_to_old_file=True)`

首先通过随意调用一个需要登录的接口来检查 Token 有效性，然后第二个实现 refresh 过程，并且默认输出（覆盖）原来的 Token 文件。

但是这样就是只能把检查和刷新交给用户代码了，不能自动检测到过期就自动刷新并且更新 Token 文件……

怎么实现自动我还在考虑……如果你有什么想法也可以提出来。

**Comment by ayanamist** [comment]
是不是可以在client请求post阶段检查一下错误，如果是过期，就主动refresh一下然后重试？

**Comment by 7sDream** [comment]
@ayanamist 

我也想过，但是除了获取基本资料的网络请求统一在 `Base` 类里，迭代器的请求统一在 `BaseGenerator` 里之外还有一些零散的操作是需要访问网络的，比如 `Me` 类的一堆操作，关注问题，评论问题，之类的……

之前没有自动刷新的需求，就没把这些请求统一到某个 API 上方便 Hook，现在修改起来有点麻烦，但是这也是个挺好的办法。

我实现的时候去查查 Requests 的文档吧，看看有没有对 `Session.request` 的 Hook 方法。

要是实在没有我就花点时间把 `Session` 封装一下，然后就应该可以了。

**Comment by cxgreat2014** [comment]
加油，等更
