### ISSUE TITLE
Login成功之后再调用相关函数为什么还要提示让登陆呢？

### ISSUE THREAD

**Issue by Ritalmc** [7sDream/zhihu-oauth#34]
f我想把获取的数据存到excel里面去，自己写了write_excel(user_id, file)函数，具体运用如下：
client = ZhihuClient()

# 登录

```python
try:
    client.login_in_terminal('##myemail', '##mypassword')
except NeedCaptchaException:
    # 保存验证码并提示输入，重新登录
    with open('a.gif', 'wb') as f:
        f.write(client.get_captcha())
    captcha = input('please input captcha:')
    client.login('email_or_phone', 'password', captcha)
client.save_token('token.pkl')
```

# 自定义函数

```python
def write_excel(user_id, file):
    rb = xlrd.open_workbook(file, formatting_info=True)
    table = rb.sheet_by_index(0)
    n = table.nrows
    wb = copy(rb)
    ws = wb.get_sheet(0)
    print('row_num', n)

    client.load_token('token.pkl')

    client_n = ZhihuClient()
    user = client_n.from_url('https://www.zhihu.com/people/'+user_id)
    print(user.name)
    writing_row = ws.row(n)  # 从第n+1行开始写
    writing_row.write(0, user.name)
    wb.save(file)
```

# 调用函数

```python
write_excel('tian-yuan-dong', 'Sample.xls')
```

# 得到的结果如下

```pytb
----- Zhihu OAuth Login -----
Login success.
row_num 6
Traceback (most recent call last):
  File "E:/python/zhihu-oauth-master/test/TRY.py", line 224, in <module>
    write_excel('tian-yuan-dong', 'Sample.xls')
  File "E:/python/zhihu-oauth-master/test/TRY.py", line 204, in write_excel
    user = client_n.from_url('https://www.zhihu.com/people/'+user_id)
  File "E:\python\zhihu-oauth-master\zhihu_oauth\utils.py", line 22, in wrapper
    raise NeedLoginException(func.__name__)
zhihu_oauth.exception.NeedLoginException: Need login to use the "from_url" method.

Process finished with exit code 1
```

请问这个怎么处理？我在自定义函数内写了client.load_token('token.pkl')不就是再次调用登录状态吗？
Python小白求教~~

**Comment by 7sDream** [comment]
@Ritalmc 

首先，你的登录代码的 `except` 区的 `client.login()` 函数里的 `email_or_phone` 和 `password` 没有换成你自己帐号密码。所以如果登录时要你输入验证码的话你会登录失败。

其次，`client.login()` 或者 `client.load_token()` 只是把自己这个 `client` 给登录了。但是在自定义函数 `write_excel` 里你又重新创建了一个 `client_n` 这个对象，它当然是没有登录的状态了。

你如果把 `client` 当成一个全局变量的话，就一直用它就好了，不用每次都建立一个新的 `client_n`。

---

另外，登录代码也可以换成更好的写法，参见：http://zhihu-oauth.readthedocs.io/zh_CN/latest/guide/login.html#recommended-way

---

有问题请继续 comment
