### ISSUE TITLE
使用时出现 ActType 未定义

### ISSUE THREAD

**Issue by cxgreat2014** [7sDream/zhihu-oauth#43]
```pytb
C:\Users\Administrator\pytwork>python login.py
Traceback (most recent call last):
  File "login.py", line 21, in <module> for act in me.activities:
  File "C:\Python27\lib\site-packages\zhihu_oauth\zhcls\generator.py", line 354, in wrapper self._get_data()
  File "C:\Python27\lib\site-packages\zhihu_oauth\zhcls\base.py", line 76, in _get_data
    raise e
zhihu_oauth.exception.GetDataErrorException: <exception str() failed>
```

**Comment by cxgreat2014** [comment]
源代码：
`# coding=utf-8

from __future__ import unicode_literals, print_function

import os

from zhihu_oauth import ZhihuClient


TOKEN_FILE = 'token.pkl'


client = ZhihuClient()

if os.path.isfile(TOKEN_FILE):
    client.load_token(TOKEN_FILE)
else:
    client.login_in_terminal()
    client.save_token(TOKEN_FILE)
me = client.me()

print('name', me.name)
print('headline', me.headline)
print('description', me.description)

print('following topic count', me.following_topic_count)
print('following people count', me.following_topic_count)
print('followers count', me.follower_count)

print('voteup count', me.voteup_count)
print('get thanks count', me.thanked_count)

print('answered question', me.answer_count)
print('question asked', me.question_count)
print('collection count', me.collection_count)
print('article count', me.articles_count)
print('following column count', me.following_column_count)
for act in me.activities:
    if act.type == ActType.CREATE_ANSWER:
        print(act.target.question.title)
`
更新token之后运行出现这个
C:\Users\Administrator\pytwork>python login.py
----- Zhihu OAuth Login -----
email: sxxcsdcdscsd
password:
Login success.
name sxsxxsx
headline cdcx
description
following topic count 2
following people count 2
followers count 1
voteup count 0
get thanks count 2
answered question 3
question asked 0
collection count 1
article count 0
following column count 1
Traceback (most recent call last):
  File "login.py", line 39, in <module>
    if act.type == ActType.CREATE_ANSWER:
NameError: name 'ActType' is not defined

C:\Users\Administrator\pytwork>

**Comment by cxgreat2014** [comment]
换到ubuntu下了，然而pip3 安装之后出现这个。。。
root@11dc24233a9d:~# ./login.py
Traceback (most recent call last):
  File "./login.py", line 5, in <module>
    from zhihu_oauth import ZhihuClient
  File "/usr/local/lib/python3.4/dist-packages/zhihu_oauth/__init__.py", line 3, in <module>
    from .client import ZhihuClient
  File "/usr/local/lib/python3.4/dist-packages/zhihu_oauth/client.py", line 11, in <module>
    import requests.packages.urllib3 as urllib3
ImportError: No module named 'requests.packages'
root@11dc24233a9d:~#
