### ISSUE TITLE
获取用户动态时有未知的活动类型 LIVE_JOIN, MEMBER_LIKE_PIN, MEMBER_CREATE_PIN, EBOOK_VOTE_UP, LIVE_PUBLISH

### ISSUE THREAD

**Issue by asrod** [7sDream/zhihu-oauth#50]
Meet a unimplemented station: Unknown activity type: LIVE_JOIN. Please send this error message to developer to get help.

Meet a unimplemented station: Unknown activity type: MEMBER_LIKE_PIN. Please send this error message to developer to get help.

**Comment by 7sDream** [comment]
又有新的类型了啊 =。=

看上去第一个是参加live，第二个是啥还不知道。

能不能提供一下是哪个用户出现的，方便我测试和修复。

今晚应该能更新个新版本。

**Comment by 7sDream** [comment]
@asrod 

`MEMBER_LIKE_PIN` 这个是赞了别人的分享……

过程中我又发现一个是 `MEMBER_CREATE_PIN`，这个是创建分享……

今晚暂时小更新一下，用 `StreamingJSON` 凑合一下。

不过想了想还是给 PIN 专门弄个类吧……这样的话开发量还不小，可能要延期到明晚才能发了。

**Comment by 7sDream** [comment]
@asrod 

0.0.29.post1

这个版本暂时修复了这个错误~不过是用 `StreamingJSON` 的，可以应急用，明晚会出一个 0.0.30。

**Comment by asrod** [comment]
ok，我已经更新啦~

**Comment by 7sDream** [comment]
因为我手机前天升级到了 7.0，由于 7.0 对 CA 证书的信任机制更改了，导致现在应用的 HTTPS 流量没法解密 =。=

很尴尬，我只好在电脑上用 Genymotion 弄了个 6.0 的虚拟机……

弄完环境有点晚了，今天就不写 LIVE 和 PIN 的类了，0.0.30 延期到下星期吧。

如果工作日有时间我就一天写一点，没时间的话就下周末了。

**Comment by doradayel** [comment]
我这也应该是同一个问题

[2016-12-19 19:01:41] base.py[line:131] ERROR Job "custom_fuction (trigger: cron[hour='19', minute='0'], next run at: 2016-12-20 19:00:00 UTC)" raised an exception
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.5/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/root/infocenter/InfoCenter/BasicAgents.py", line 70, in custom_fuction
    ebook_path = object_crawler.run()
  File "/root/infocenter/InfoCenter/CustomApps/zhihu_timeline.py", line 75, in run
    for act in ifp.activities:
  File "/root/anaconda3/lib/python3.5/site-packages/zhihu_oauth/zhcls/generator.py", line 174, in __next__
    obj = self[self._index]
  File "/root/anaconda3/lib/python3.5/site-packages/zhihu_oauth/zhcls/generator.py", line 151, in __getitem__
    return self._build_obj(self._data[item])
  File "/root/anaconda3/lib/python3.5/site-packages/zhihu_oauth/zhcls/generator.py", line 261, in _build_obj
    return Activity(data, self._session)
  File "/root/anaconda3/lib/python3.5/site-packages/zhihu_oauth/zhcls/activity.py", line 113, in __init__
    self._type = _verb_to_type(data['verb'])
  File "/root/anaconda3/lib/python3.5/site-packages/zhihu_oauth/zhcls/activity.py", line 70, in _verb_to_type
    'developer to get help.'.format(verb))
zhihu_oauth.exception.UnimplementedException: Meet a unimplemented station: Unknown activity type: MEMBER_CREATE_PIN. Please send this error message to developer to get help.

**Comment by 7sDream** [comment]
升级到最新版本即可。

doradayel <notifications@github.com>于2016年12月20日周二 10:25写道：

**Comment by 7sDream** [comment]
如果再遇到类似问题，不过type是 EBOOK _VOTE_UP 的话，升级到 0.0.29.post2 即可。

**Comment by 7sDream** [comment]
类似的，如果遇到 LIVE_PUBLISH 类型的，升级到 0.0.30 即可。
