### ISSUE TITLE
关于测试

### ISSUE THREAD

**Issue by robotcator** [7sDream/zhihu-oauth#52]
我对这个项目挺感兴趣的，因为平时也经常玩知乎的缘故吧。
但是下clone这个项目下来后，运行了test_client_from_url.py代码，发现报如下错误。
```
from .client_test_base import ZhihuClientClassTest
ValueError: Attempted relative import in non-package
```
我不太懂项目测试过程，所以在这里借这个项目请教一下。

实验环境：
Python 2.7.6 (default, Jun 22 2015, 18:00:18) 
[GCC 4.8.2] on linux2

ps：还有中文注释貌似会有问题？
SyntaxError: Non-ASCII character '\xe6' in file xxx/zhihu-oauth/zhihu_oauth/zhcls/message.py on line 43

在代码开头加上#-*- coding=utf-8 -*-就好了。

**Comment by robotcator** [comment]
好的。

**Comment by 7sDream** [comment]
@robotcator 

目前测试的流程是：

1. 在 test 目录里生成 token 文件，并且命名为 `token.pkl`
2. 需要在项目的根目录（test 目录之外）执行命令 `python -m unittest discover`（如果你是在 Linux 上用 Python 3 的话，把命令里的换成 `python3`）

（用到的是 unittest 这个 built-in package，可以自行看官方文档）

一般来说测试结果大概如下：

![](http://rikka-10066868.image.myqcloud.com/109e5e9f-a5f8-41d7-adc0-8513fff4c91c.png)

如果没有 token 文件就会出现：

![](http://rikka-10066868.image.myqcloud.com/1779d29a-5e05-484e-9268-70f97eed52da.png)

如果你是用生成 Token 文件时的 Python 版本和测试的 Python 版本不一样，就会出现：

![](http://rikka-10066868.image.myqcloud.com/2b92e405-af4c-4421-b814-9ed2f5fb4685.png)

---

但是其实这个项目的测试还很不完善……基本处于没有的状态 =。=

**Comment by robotcator** [comment]
谢谢。使用unittest测试案例自动搜索没有问题，如果我想单独测试某个文件或者模块。
我使用如下命令，出现错误。
```
(1) python -m unittest test/test_client_from_url

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
ImportError: Import by filename is not supported.
```
```
 (2) python -m unittest test                                

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

```
而使用以下命令确是可以的
```
 (3) python -m unittest test.test_client_from_url

no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
----------------------------------------------------------------------
Ran 14 tests in 0.000s

OK (skipped=14)

```
```
(4) python -m unittest test.test_client_create_zhihu_object

no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
----------------------------------------------------------------------
Ran 8 tests in 0.000s

OK (skipped=8)
```
```
(5) python -m unittest test.test_client_create_zhihu_object.TestZhihuClientFromURL

no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
no token file, skip all tests.
s
----------------------------------------------------------------------
Ran 8 tests in 0.000s

OK (skipped=8)
```
```
(6)  python -m unittest test.test_client_create_zhihu_object.TestZhihuClientFromURL.test_answer_id_must_be_int

no token file, skip all tests.
s
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK (skipped=1)
```
按照文档https://docs.python.org/2/library/unittest.html#command-line-interface里面的描述，3和4属于测试模块，5属于测试模块中的某个类 classes， 而6属于测试模块中某个类的方法。  那么1和2为什么会出错？

还有token文件，我只看到/zhihu_oauth/oauth/token.py文件中其结构，这是自己写入生成么？还是通过其他方法？

**Comment by 7sDream** [comment]
(1) 这种用法本身就不支持的吧，应该用你后面的 (3) 那种方法。

(2) 没用的原因是 `test/__init__.py` 这个文件是空的，直接 import test 这个 module 其实什么都没导入，所以不会运行任何测试。你可以试试往这个文件里加一行

```python
from .test_client_from_url import *
```

然后再在 test 目录外运行

```bash
python -m unittest test
````

就相当于运行了 `test_client_from_url` 这个的所有测试了。

---

Token 文件的生成可以看文档的登录部分：http://zhihu-oauth.readthedocs.io/zh_CN/latest/guide/login.html
